### ISSUE TITLE
camera.map not updating unless browser refresh

### ISSUE THREAD

**Issue by matt8707** [TheLastProject/lovelace-valetudo-map-card#84]
Is there something that has to be done on the user side so that camera.map updates the vacuum position on the map?

lovelace-valetudo-map-card 2021-02-17
Firmware: 2021.02.0 (Valetudo)
home assistant 2021.2.3

```
type: 'custom:valetudo-map-card'
entity: camera.map
rotate: 0
crop:
  top: 0
  bottom: 0
  left: 0
  right: 0
min_height: 0
```

**Comment by TheLastProject** [comment]
Looking at the code more, I think @Hypfer accidentally made vacuum_entity a semi-required field on this card or the card would only update every 2 minutes.

Could you please update lovelace-valetudo-map-card to the latest beta version in HACS? I think I fixed it in https://github.com/TheLastProject/lovelace-valetudo-map-card/commit/fdbc594cb0cbf3c21708682c70e0528d06ac6fd1.

**Comment by matt8707** [comment]
That didn't seem to fix it, but you're right about `vacuum_entity`, that works

**Comment by TheLastProject** [comment]
Are you absolutely sure you are using the latest version and did you clear your browser cache after updating?

**Comment by matt8707** [comment]
I did, tried disabling cache altogether and now it works..... even without `vacuum_entity`, thank you

**Comment by TheLastProject** [comment]
Awesome, thank you for confirming it fixed it for you :)
